---
version: "3.8"
services:
  raga-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .build/:/usr/local/bin
    restart: always